replicaCount: 1

image:
  repository: registry.registry.svc.cluster.local:5000/echo-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: echo.homelab.local

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    memory: 64Mi

healthcheck:
  path: /healthz
  port: 8080

serviceAccount:
  create: true
