apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: env-quota
  namespace: prod
spec:
  hard:
    requests.memory: 1Gi
    limits.memory: "1536Mi"
    requests.cpu: 500m
    limits.cpu: "2"
