apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server-dev
  namespace: argocd
  labels:
    homelab/tier: app
    homelab/app: echo-server
    homelab/project: demo
    homelab/env: dev
  annotations:
    kargo.akuity.io/authorized-stage: echo-server:dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AaronRoethe/homelab
    targetRevision: master
    path: apps/echo-server/chart
    helm:
      releaseName: echo-server
      valuesObject:
        image:
          repository: ghcr.io/aaronroethe/echo-server
          tag: 0.1.1
          pullPolicy: Always
        ingress:
          host: echo-dev.homelab.local
        config:
          env:
            LOG_LEVEL: "debug"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
