apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-server.fullname" . }}
  labels:
    {{- include "echo-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echo-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "echo-server.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.healthcheck.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.path }}
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          {{- if or .Values.config.env .Values.config.secret }}
          volumeMounts:
            {{- if .Values.config.env }}
            - name: config-env
              mountPath: /app/config/env
              readOnly: true
            {{- end }}
            {{- if .Values.config.secret }}
            - name: config-secret
              mountPath: /app/config/secret
              readOnly: true
            {{- end }}
          {{- end }}
      {{- if or .Values.config.env .Values.config.secret }}
      volumes:
        {{- if .Values.config.env }}
        - name: config-env
          configMap:
            name: {{ include "echo-server.fullname" . }}-env
        {{- end }}
        {{- if .Values.config.secret }}
        - name: config-secret
          secret:
            secretName: {{ include "echo-server.fullname" . }}-secret
        {{- end }}
      {{- end }}
