apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace: argocd
  labels:
    homelab/tier: app
    homelab/app: echo-server
    homelab/project: demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/aroethe/homelab
      targetRevision: main
      path: apps/echo-server/chart
      helm:
        valueFiles:
          - $overlays/platform/apps/demo/overlays/dev/echo-server/values.yaml
    - repoURL: https://github.com/aroethe/homelab
      targetRevision: main
      ref: overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
