apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-projects
  namespace: argocd
  labels:
    homelab/tier: platform
    homelab/app: kargo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AaronRoethe/homelab
    targetRevision: master
    path: platform/kargo/projects
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
