apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  labels:
    homelab/tier: platform
    homelab/app: registry
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: Update to your repo URL
    repoURL: https://github.com/aroethe/homelab
    path: platform/base/registry
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
