apiVersion: v1
kind: Secret
metadata:
  name: local-registry
  namespace: echo-server
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: registry.registry.svc.cluster.local:5000
  insecure: "true"
