apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: echo-server
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: echo-server
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/AaronRoethe/homelab
            checkout:
              - branch: master
                path: ./src
        - uses: yaml-update
          as: update-image
          config:
            path: ./src/platform/apps/demo/dev/echo-server.yaml
            updates:
              - key: spec.source.helm.valuesObject.image.tag
                value: ${{ imageFrom("ghcr.io/aaronroethe/echo-server").Tag }}
        - uses: git-commit
          config:
            path: ./src
            messageFromSteps:
              - update-image
        - uses: git-push
          as: push
          config:
            path: ./src
        - uses: argocd-update
          config:
            apps:
              - name: echo-server-dev
