apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: echo-server
  namespace: echo-server
spec:
  subscriptions:
    - image:
        repoURL: registry.infra.svc.cluster.local:5000/echo-server
        semverConstraint: ">=0.1.0"
        discoveryLimit: 5
