api:
  adminAccount:
    enabled: true
    passwordHash: "$2y$10$SYnhoOjBxdnyEhHSLuFR8uOtFfTxhElgL/zjtUc3tPaZqcpmBwhGC"
    tokenSigningKey: "9gwWKPKj+v+OUKSaw2bnMc6xXhXWJqHpm6BauYLGsLU="
  service:
    type: NodePort
    nodePort: 30081
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi

managementController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

webhooksServer:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
