apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server-staging
  namespace: argocd
  labels:
    homelab/tier: app
    homelab/app: echo-server
    homelab/project: demo
    homelab/env: staging
  annotations:
    kargo.akuity.io/authorized-stage: echo-server:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AaronRoethe/homelab
    targetRevision: master
    path: apps/echo-server/chart
    helm:
      releaseName: echo-server
      valuesObject:
        image:
          tag: "0.1.0"
        ingress:
          host: echo-staging.homelab.local
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
