apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server-staging
  namespace: argocd
  labels:
    homelab/tier: app
    homelab/app: echo-server
    homelab/env: staging
    kargo.akuity.io/authorized-stage: echo-server:staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Base chart from app repo
    - repoURL: https://github.com/aroethe/homelab
      targetRevision: main
      path: apps/echo-server/chart
      helm:
        valueFiles:
          - $overlays/platform/overlays/echo-server/values-pi.yaml
          - $overlays/platform/overlays/echo-server/values-staging.yaml
    # Overlay values from platform
    - repoURL: https://github.com/aroethe/homelab
      targetRevision: main
      ref: overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
