apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-echo-server-staging
  namespace: argocd
  labels:
    homelab/tier: app
    homelab/project: demo
spec:
  project: default
  source:
    repoURL: https://github.com/aroethe/homelab
    targetRevision: main
    path: platform/apps/demo/overlays/staging/echo-server
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
